# Generated by Django 2.2.7 on 2019-11-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellidos', models.CharField(max_length=30)),
                ('Edad', models.CharField(max_length=3)),
                ('Sexo', models.CharField(max_length=7)),
                ('Direccion', models.CharField(max_length=50)),
                ('Carrera', models.CharField(max_length=18)),
            ],
        ),
    ]
