# Generated by Django 2.2.7 on 2019-11-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
    ]
